# Generated by Django 3.2.18 on 2023-05-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=288)),
                ('idade', models.IntegerField()),
                ('cpf', models.IntegerField()),
            ],
        ),
    ]
