# Generated by Django 3.2.18 on 2023-05-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id_tudo', models.AutoField(primary_key=True, serialize=False)),
                ('nomes', models.TextField(max_length=255)),
                ('sobrenome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('celular', models.TextField(max_length=255)),
                ('funcao', models.TextField(max_length=266)),
                ('escolaridade', models.TextField(max_length=233)),
                ('referencias', models.TextField(max_length=233)),
                ('estadocivil', models.TextField(max_length=233)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
